{{- if .Values.kibana.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}-fluentd
{{- if .Values.fluentd.namespace }}
  namespace: {{ .Values.fluentd.namespace }}
{{- end }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ template "fullname" . }}-fluentd
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      component: {{ template "fullname" . }}-fluentd
  template:
    metadata:
      labels:
        component: {{ template "fullname" . }}-fluentd
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: {{ .Values.image.fluentd.repository }}:{{ .Values.image.fluentd.tag }}
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: '{{ template "fullname" . }}{{ .Values.client.serviceType.internal.suffix }}.{{ .Release.Namespace }}.svc.cluster.local'
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "{{ .Values.service.httpPort }}"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "{{ .Values.service.httpScheme }}"
          {{- range $key, $value :=  .Values.fluentd.env }}
          - name: {{ $key }}
            value: "{{ $value | quote }}"
          {{- end }}
        resources:
{{ toYaml .Values.fluentd.resources | indent 12 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
{{- end }}
